### ISSUE TITLE
Unable to customise style of search input text

### ISSUE THREAD

**Issue by sagar7993** [AdelRedaa97/react-native-select-dropdown#103]
I am trying to apply styles on the text field inside search input, but properties such as color / font size etc do not work

searchInputStyle={{ color: 'red', fontSize: 20 }}

Am I missing something here?

**Comment by sagar7993** [comment]
Looks like a PR for this fix already exists ->

https://github.com/AdelRedaa97/react-native-select-dropdown/pull/82/files

**Comment by AdelRedaa97** [comment]
Merged
