### ISSUE TITLE
Array of object is not working

### ISSUE THREAD

**Issue by avijit-ordering** [AdelRedaa97/react-native-select-dropdown#106]
Hello, 

Please check this screen. 

https://user-images.githubusercontent.com/16749307/207792055-d5baf387-050e-4542-b411-ccc6afa62054.mp4

Please help me for this problem.

Thanks

**Comment by joshuakwak** [comment]
On buttonTextAfterSelection instead of
**return selectedItem;** 
Make it 
**return selectedItem.name;**

Same way to the rowTextForSelection, make it
**return item.name;**

**Comment by deveshlashkari** [comment]
> On buttonTextAfterSelection instead of **return selectedItem;** Make it **return selectedItem.name;**
> 
> Same way to the rowTextForSelection, make it **return item.name;**

Works like a charm✅
