### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by swrobel** [AdelRedaa97/react-native-select-dropdown#107]
It would be really helpful to have a [CHANGELOG](https://keepachangelog.com) either in a file, or github releases. At a minimum, please tag versions so that we can compare & see what's changed. Appreciate your work!

**Comment by AdelRedaa97** [comment]
Added in v4.0 take a look at the changes made in v4.0
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
