### ISSUE TITLE
Define styles for defaultButtonText (placeholder)

### ISSUE THREAD

**Issue by xnejp03** [AdelRedaa97/react-native-select-dropdown#108]
It's be nice to be able to define different style for the placeholder text (eg color).

Is it currently possible?

**Comment by joshuakwak** [comment]
Use buttonTextStyle prop

buttonTextStyle={{
  color:  'white',
}}

**Comment by xnejp03** [comment]
But won't that then affect the selected colour too? I want placeholder to
be different from the eventual value being selected.

**Comment by joshuakwak** [comment]
I used State

![image](https://user-images.githubusercontent.com/54160965/208398695-6809f2c6-6799-4e14-b548-cb7c280c65cf.png)
![image](https://user-images.githubusercontent.com/54160965/208398771-72ff31e0-3350-4947-bd56-2f44fc30cc4f.png)

hopefully it helps.

**Comment by xnejp03** [comment]
Thanks.

**Comment by satyabrata-dash5** [comment]
Not working
