### ISSUE TITLE
How to adjust the backdrop shadow when list item is activated

### ISSUE THREAD

**Issue by ALIFKI** [AdelRedaa97/react-native-select-dropdown#11]

**Comment by ALIFKI** [comment]
![image](https://user-images.githubusercontent.com/45888967/127114037-d31b7129-42f4-47cd-8342-fa82e2511c21.png)
try to change backdrop shadow in this dropdown

**Comment by AdelRedaa97** [comment]
You can use `renderCustomizedRowChild` prop see example no 4 in examples/demo1.js you can change style of row if it's the selected one
