### ISSUE TITLE
I need onRequestClose prop of React Native Modal 

### ISSUE THREAD

**Issue by yashpatel100** [AdelRedaa97/react-native-select-dropdown#110]
I need to come back  when clicking on the android back button 
like below code 

import React from 'react';
import {Modal} from 'react-native';
import { useNavigation } from '@react-navigation/native'

const DropdownModal = ({setIsVisible, visible, statusBarTranslucent, children}) => {
  const navigation = useNavigation();
  const defaults = {
    statusBarTranslucent: statusBarTranslucent || false,
  };
  return (
    <Modal
      **onRequestClose={()=>{
        setIsVisible(false)
        navigation.goBack()
      }}**
      supportedOrientations={['portrait', 'landscape']}
      animationType="none"
      transparent={true}
      statusBarTranslucent={defaults.statusBarTranslucent}
      visible={visible}>
      {children}
    </Modal>
  );
};
export default DropdownModal;

**Comment by btooom1999** [comment]
i am using 3.3.0 version, try this by patch-package

diff --git a/node_modules/react-native-select-dropdown/src/SelectDropdown.js b/node_modules/react-native-select-dropdown/src/SelectDropdown.js
index a59b78d..3bdac77 100644
--- a/node_modules/react-native-select-dropdown/src/SelectDropdown.js
+++ b/node_modules/react-native-select-dropdown/src/SelectDropdown.js
@@ -166,7 +166,7 @@ const SelectDropdown = (
   const renderDropdown = () => {
     return (
       isVisible && (
-        <DropdownModal statusBarTranslucent={statusBarTranslucent} visible={isVisible}>
+        <DropdownModal onRequestClose={closeDropdown} statusBarTranslucent={statusBarTranslucent} visible={isVisible}>
           <DropdownOverlay onPress={closeDropdown} backgroundColor={dropdownOverlayColor} />
           <DropdownWindow layoutStyle={dropdownWindowStyle}>
             <FlatList
diff --git a/node_modules/react-native-select-dropdown/src/components/DropdownModal.js b/node_modules/react-native-select-dropdown/src/components/DropdownModal.js
index c6ca06e..9f096c2 100644
--- a/node_modules/react-native-select-dropdown/src/components/DropdownModal.js
+++ b/node_modules/react-native-select-dropdown/src/components/DropdownModal.js
@@ -1,7 +1,7 @@
 import React from 'react';
 import {Modal} from 'react-native';
 
-const DropdownModal = ({visible, statusBarTranslucent, children}) => {
+const DropdownModal = ({visible, statusBarTranslucent, children, onRequestClose}) => {
   const defaults = {
     statusBarTranslucent: statusBarTranslucent || false,
   };
@@ -10,6 +10,7 @@ const DropdownModal = ({visible, statusBarTranslucent, children}) => {
       supportedOrientations={['portrait', 'landscape']}
       animationType="none"
       transparent={true}
+      onRequestClose={onRequestClose}
       statusBarTranslucent={defaults.statusBarTranslucent}
       visible={visible}>
       {children}

**Comment by AdelRedaa97** [comment]
Thanks, @btooom1999 this issue has been fixed in v3.3.2 in this commit 743d62e
