### ISSUE TITLE
Search box flickers while searching on iOS

### ISSUE THREAD

**Issue by aryalprakash** [AdelRedaa97/react-native-select-dropdown#113]
It works fine on android but flickers on iOS.
I'm using version `3.2.1`

https://user-images.githubusercontent.com/3658290/213921062-690a4736-a745-4c6f-939d-8f31186c3dd1.mov

**Comment by AdelRedaa97** [comment]
Could you try any of these examples and tell me if this flickers still exist 
https://github.com/AdelRedaa97/react-native-select-dropdown/blob/master/examples/demo3.js
