### ISSUE TITLE
blank screen Dispaly for large list on scroll

### ISSUE THREAD

**Issue by sagarjeu** [AdelRedaa97/react-native-select-dropdown#115]
when scrolling fast blank screen is displayed.

**Comment by AdelRedaa97** [comment]
If your case is the same as these issues.
https://github.com/AdelRedaa97/react-native-select-dropdown/issues/69
https://github.com/AdelRedaa97/react-native-select-dropdown/issues/79

You can use `onScrollEndReached` prop for pagination
