### ISSUE TITLE
buttonStyle not working

### ISSUE THREAD

**Issue by minh-dai** [AdelRedaa97/react-native-select-dropdown#117]
![Screen Shot 2023-02-02 at 20 48 09](https://user-images.githubusercontent.com/24986640/216342101-71b16193-734c-4caa-b3e3-8cad593b266a.png)

My code like this image, but buttonStyle not working.

**Comment by KatuGT** [comment]
same for me with [styles.input, isFocused && styles.outLine]

**Comment by AdelRedaa97** [comment]
Fixed in v3.3.0, thanks to @raychanks
