### ISSUE TITLE
Dropdown cannot be closed in iOS simulator

### ISSUE THREAD

**Issue by swrobel** [AdelRedaa97/react-native-select-dropdown#118]
I have never experienced this problem on a real device, but 100% of the time in the iOS simulator. I can't click any of the dropdown items, or click outside of the dropdown to close it. Reloading via the Metro console doesn't dismiss the dropdown - it renders on top of any other screens until the app is killed & restarted on the simulator. Here's an example of what it looks like just floating there after reloading the app via Metro (what is shown is a completely different screen than the one that even contains the dropdown):
![simulator_screenshot_540CE565-3670-46F3-BCCF-061A30B2C57B](https://user-images.githubusercontent.com/157270/217726183-f65fb081-3c1d-4384-8028-38cdcfcba4c6.png)

**Comment by swrobel** [comment]
select-dropdown version 3.3.0. I do not have this issue with Modals.

**Comment by AdelRedaa97** [comment]
can you add the code that is in React native's documentation [https://reactnative.dev/docs/modal]() in the same screen where you add the dropdown?

**Comment by AdelRedaa97** [comment]
I mean this code 
```
<Modal
        animationType="slide"
        transparent={true}
        visible={modalVisible}
        onRequestClose={() => {
          Alert.alert('Modal has been closed.');
          setModalVisible(!modalVisible);
        }}>
        <View style={styles.centeredView}>
          <View style={styles.modalView}>
            <Text style={styles.modalText}>Hello World!</Text>
            <Pressable
              style={[styles.button, styles.buttonClose]}
              onPress={() => setModalVisible(!modalVisible)}>
              <Text style={styles.textStyle}>Hide Modal</Text>
            </Pressable>
          </View>
        </View>
      </Modal>
```

**Comment by swrobel** [comment]
Interesting! The modal can't be dismissed from that screen either...
