### ISSUE TITLE
How to set selected index from js

### ISSUE THREAD

**Issue by irfan-globiance** [AdelRedaa97/react-native-select-dropdown#119]
hi  get the data from API and want to set select index on runtime

**Comment by AdelRedaa97** [comment]
Is that what you want to achieve?

```
dropdownRef.current.selectIndex(2) 

....
....

<SelectDropdown ref={dropdownRef} >
```

**Comment by Siliconvelly** [comment]
but the thing is not working bro i want to reset my dropdown when i select first the other dropdown should be reset the value because it is connected to above or first dropdown

**Comment by AdelRedaa97** [comment]
dropdownRef.current.reset()
