### ISSUE TITLE
Dropdown box full width

### ISSUE THREAD

**Issue by TomasBalaguer** [AdelRedaa97/react-native-select-dropdown#12]
How can i make the dropdown box ocuppies full width??

**Comment by AlixH** [comment]
Have you tired buttonStyle={{width: '100%'}} ?

**Comment by ankitdigikit** [comment]
yes, but it's not working

**Comment by ankitdigikit** [comment]
How to add a specific style or some icon in that select box

**Comment by nicolasguzca** [comment]
Same issue here...
