### ISSUE TITLE
buttonTextAfterSelection not cleared 

### ISSUE THREAD

**Issue by satyabrata-dash5** [AdelRedaa97/react-native-select-dropdown#127]
when trying to clear dropdown buttonTextAfterSelection is there so the dropdown not cleared at that moment

**Comment by AdelRedaa97** [comment]
A lot of changes have been made in v4.0, fixing these issues
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
