### ISSUE TITLE
I want to show empty text inside dropdown when there is no data available.So How I achieve this scenario in this package?

### ISSUE THREAD

**Issue by amannarola** [AdelRedaa97/react-native-select-dropdown#131]
I want to show empty text inside dropdown when there is no data available.So How I achieve this scenario in this package?

**Comment by DMaxence** [comment]
Just put a space instead of an empty text `defaultButtonText={' '}`

**Comment by AdelRedaa97** [comment]
A lot of changes were made in v4.0, take a look here
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
