### ISSUE TITLE
defaultButtonText color

### ISSUE THREAD

**Issue by ildibicaku** [AdelRedaa97/react-native-select-dropdown#135]
Is there any way i can change the color of defaultButtonText ? 
Lets say I want  defaultButtonText  color gray and when I selected one of the values the value to appear black

**Comment by aqifkhan** [comment]
I searched, but didn't find anything for changing defaultButtonText.
But you can change it from your side using useState. 
I will share an example 

 const [defaultColorGender, setDefaultColorGender] = useState('gray')   **// Here you can use your default color**

 <SelectDropdown
     dropdownStyle={{ borderRadius: 15 }}
     data={gender}
     renderDropdownIcon={DropDownIcon}
     buttonStyle={{ width: '90%', backgroundColor: '#FFFFFF' }}
    onSelect={(selectedItem, index) => {
     setDefaultColorGender('#000000')       **// As you select any option from dropdown then you can change color of your button**
      }}
     selectedRowStyle={{ backgroundColor: '#F4F7FF' }}
     selectedRowTextStyle={{ color: COLORS.Primary,fontFamily: FONTS.Medium  }}
     rowStyle={{ backgroundColor: '#FFFFFF' }}
      rowTextStyle={{ textAlign: 'left', paddingLeft: 5, fontSize: 14 ,fontFamily: FONTS.Medium }}
      defaultButtonText='Add your gender'
      buttonTextStyle={{ color:defaultColorGender }}      **// In start You will get your default color here**
          />

**Comment by ildibicaku** [comment]
Thank you @aqifkhan

**Comment by AdelRedaa97** [comment]
A lot of changes were made in v4.0, take a look here
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists

**Comment by dominictobias** [comment]
Text color has no effect for some reason, using exactly same code as demo.

```
renderItem={(item, index, isSelected) => {
        return (
          <View
            style={[
              styles.dropdownItemStyle,
              isSelected && { backgroundColor: '#D2D9DF' },
            ]}
          >
            <Text style={styles.dropdownItemTxtStyle}>
              {item.title}
            </Text>
          </View>
        )
      }}
      
dropdownItemTxtStyle: {
    flex: 1,
    fontSize: 18,
    color: '#151E26',
  }
```

<img width="222" alt="Screenshot 2024-05-30 at 3 43 03 PM" src="https://github.com/AdelRedaa97/react-native-select-dropdown/assets/160451465/76add668-d4e5-48e7-a0a0-a420bcb3ffe2">

Adding a `backgroundColor` shows the item is actually there though:

<img width="221" alt="Screenshot 2024-05-30 at 3 44 19 PM" src="https://github.com/AdelRedaa97/react-native-select-dropdown/assets/160451465/5062658a-a69b-4a94-a3f0-c76123a8a785">
