### ISSUE TITLE
Show/render empty component?

### ISSUE THREAD

**Issue by Jamal-ReachFirst** [AdelRedaa97/react-native-select-dropdown#136]
On search function if search array is empty it show a blank view.

Can we show/render an empty component if no data is available.

**Comment by Jamal-ReachFirst** [comment]
Any progress on this?

**Comment by owonie** [comment]
> @AdelRedaa97 Any progress on this?

I just added empty row child props and deployed it as a customzized library. You could use it if you want it :) 

Here is  the link https://www.npmjs.com/package/react-native-select-dropdown-customized

**Comment by Jamal-ReachFirst** [comment]
Please update the main package and close this issue.

**Comment by owonie** [comment]
> Please update the main package and close this issue.

sure! thank you for reply :)

**Comment by AdelRedaa97** [comment]
Fixed in v4.0 take a look at the changes made in v4.0
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists

**Comment by saidinusah** [comment]
hi, not seeing anything related to the mentioned issue, please assist @AdelRedaa97

**Comment by Jamal-ReachFirst** [comment]
@AdelRedaa97 please reopen this issue
