### ISSUE TITLE
React Native TypeError: undefined is not an object (evaluating 'props.getItem')

### ISSUE THREAD

**Issue by web-2017** [AdelRedaa97/react-native-select-dropdown#139]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-26 at 13 45 26](https://github.com/AdelRedaa97/react-native-select-dropdown/assets/29303396/36487237-4e4c-41f4-8170-869fdcb70885)

const [selected, setSelected] = useState([
		{ key: 1, value: 'PieChart' },
		{ key: 2, value: 'Table' },
])

<SelectDropdown
        data={selected}
        onSelect={(selectedItem, index) => {
            console.log(selectedItem, index)
        }}
        buttonTextAfterSelection={(selectedItem, index) => {
        // text represented after item is selected
        // if data array is an array of objects then return selectedItem.property to render after item is selected
              return selectedItem
        }}
        rowTextForSelection={(item, index) => {
        // text represented for each item in dropdown
        // if data array is an array of objects then return item.property to represent item in dropdown
                return item
        }}
/>

**Comment by AdelRedaa97** [comment]
You are passing an array of objects, to render a title for the button after selection use ```return selectedItem.value``` and for each row use ```return item.value```
