### ISSUE TITLE
styles not working in IOS

### ISSUE THREAD

**Issue by RonakBansal321** [AdelRedaa97/react-native-select-dropdown#143]
in below dropdown this 3 styles are not working for IOS , for android it is working fine.|
 
 shadowOpacity: 0.3,
  elevation: 3,
  shadowOffset: { width: 0.1, height: 0.1 },
  
  <SelectDropdown
                data={GenderData.map((name) => {
                  return name.name;
                })}
                onSelect={(name, value) => {
                  setGender({ name, value }); //{"name": "Male", "value": 1}
                }}
                buttonStyle={{
                  width: wp("43.3%"),
                  height: hp("4.5%"),
                  backgroundColor: "#ffffff",
                  borderRadius: 8,
                  borderWidth: 0.4,
                  borderColor: "#d3d3d3",
                  shadowOpacity: 0.3,
                  elevation: 3,
                  shadowOffset: { width: 0.1, height: 0.1 },
                  justifyContent: "space-between",
                }}
                dropdownStyle={{
                  borderRadius: 8,
                  backgroundColor: "#ffffff",
                  shadowOpacity: 0.3,
                  elevation: 3,
                  shadowOffset: { width: 0.1, height: 0.1 },
                }}
                dropdownOverlayColor="false"
                buttonTextStyle={{
                  fontSize: hp("1.6%"),
                  flex: 0.7,
                }}
                rowStyle={{
                  width: wp("45%"),
                  height: 32,
                  backgroundColor: "#ffffff",
                }}
                defaultValue={gender.name}
                rowTextStyle={{
                  color: "#6159a1",
                  fontSize: hp("1.45%"),
                  textAlign: "left",
                  marginLeft: wp("3.75%"),
                }}
                renderDropdownIcon={() => (
                  <Icon size={15} color={"#6159a1"} name="caret-down" />
                )}
                dropdownIconPosition="right"
                defaultButtonText={Strings.select_gender_new}
              />

**Comment by RonakBansal321** [comment]
> overflow: 'visible'

Thanks buddy 
it worked.

**Comment by lucyanddarlin** [comment]
when I add overflow: 'visible' in dropdownStyle, I find `borderRadius` doesn't work, please help me, thanks a lot!
