### ISSUE TITLE
Dropdown Menu offset

### ISSUE THREAD

**Issue by andrehadianto** [AdelRedaa97/react-native-select-dropdown#144]
The menu offset is different for different platform
<img width="908" alt="image" src="https://github.com/AdelRedaa97/react-native-select-dropdown/assets/40631483/1035a583-d463-4faf-a14e-0f789887c615">

Would be great if there is a prop for `menuOffset` as well. Additionally, `placement` would be great.

**Comment by AdelRedaa97** [comment]
It's about android's StatusBar try to use this prop in Dropdown ```<SelectDropdown statusBarTranslucent={true}```

or make ```<StatusBar translucent={false} />```

**Comment by derickdecesare** [comment]
> It's about android's StatusBar try to use this prop in Dropdown `<SelectDropdown statusBarTranslucent={true}`
> 
> or make `<StatusBar translucent={false} />`

Thank you this worked! 👍

**Comment by OzgunOzdemir** [comment]
> It's about android's StatusBar try to use this prop in Dropdown `<SelectDropdown statusBarTranslucent={true}`
> 
> or make `<StatusBar translucent={false} />`

Thanks. It worked for me 🎉
