### ISSUE TITLE
Hide separator between options or change color of separator

### ISSUE THREAD

**Issue by SmritiSYadav** [AdelRedaa97/react-native-select-dropdown#145]
How can I hide or change color of separator in options?

**Comment by rodrigosborges** [comment]
Just add rowStyle={{borderBottomWidth: 0}} to the properties

**Comment by AdelRedaa97** [comment]
A lot of changes were made in v4.0, take a look here
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
