### ISSUE TITLE
Dropdown for android shows up about 30px below the dropdown button

### ISSUE THREAD

**Issue by derickdecesare** [AdelRedaa97/react-native-select-dropdown#149]
Hi, so this component works as expected on IOS. However on android when the dropdown menu is selected it appears about 40px below the dropdown button which is undesirable. 

I have attached a screenshot so you can see the issue. 

It doesn't seem that the position is directly changeable, so I've had a hard time trying to find a workaround with this problem. 
![Screenshot_20230726-174819](https://github.com/AdelRedaa97/react-native-select-dropdown/assets/105116994/49a9e003-f7e0-4535-a91b-033d43e1fd90)

**Comment by isidoreony** [comment]
I fixed mine with this link https://github.com/AdelRedaa97/react-native-select-dropdown/issues/144#issuecomment-1623541407
