### ISSUE TITLE
Is there any option for MultiSelection ?

### ISSUE THREAD

**Issue by OrataroSunsoftapp** [AdelRedaa97/react-native-select-dropdown#15]

**Comment by AdelRedaa97** [comment]
Unfortunately there is no option for multi selecting for now but it will be added soon

**Comment by troynguyen8** [comment]
@AdelRedaa97 was this ever added?

**Comment by AhmedHF** [comment]
any updates?

**Comment by pokhiii** [comment]
@AdelRedaa97 Did it get added?
