### ISSUE TITLE
Device Text Size Not Reflected

### ISSUE THREAD

**Issue by mattlewer** [AdelRedaa97/react-native-select-dropdown#152]
Hi there,

When using this dropdown library (which is lovely btw), the font size won't increase when it is set to a larger size within the device settings. This is proving to be an issue with accessibility, and also looks stylistically bad when coupled with text sizes that DO increase with the device settings.

In the following example both the postcode field and the dropdown have the same typography settings applied:
![processed-bd49aa1f-ebd7-4fc6-a7f5-cf4f877731ed_VPCdft0n](https://github.com/AdelRedaa97/react-native-select-dropdown/assets/42501880/1da26f80-d2d0-4207-a051-9df13095dd87)

**Comment by kitkline** [comment]
Hi there - a quick bump for this question as we find the same. We've just moved to this library after endless issues with the one we used before and love it! But also noted it does not honor the device accessibility text size. 

Any fix for this or a work around?

Thanks for a fab library!

Cheers
Kit

**Comment by AdelRedaa97** [comment]
Fixed in v4.0 take a look at the changes made in v4.0
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
