### ISSUE TITLE
Modal does not reset height after search results change

### ISSUE THREAD

**Issue by mattlewer** [AdelRedaa97/react-native-select-dropdown#155]
I fire an API request when the user searches which then populates the dropdown list, unfortunately the modal does not re-establish it's height and therefore the results run off the screen with no way to access them.

I would expect the modal to reduce it's height to fit. I've fixed this by hardcoding the height, but i'd rather it was responsive. In the example below my drop down had borders top and bottom, but as you can see, the bottom is off the screen.

![Screenshot 2023-09-20 at 10 34 29](https://github.com/AdelRedaa97/react-native-select-dropdown/assets/42501880/94bfba68-6426-4210-8a12-03e0388db147)

**Comment by AdelRedaa97** [comment]
Fixed in v4.0 take a look at the changes made in v4.0
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
