### ISSUE TITLE
buttonTextAfterSelection method doesn't work when "createAsyncThunk" (redux-toolkit) calls in onSelect

### ISSUE THREAD

**Issue by hasanhasanov** [AdelRedaa97/react-native-select-dropdown#160]
When the `createAsyncThunk` _(redux-toolkit)_ method is called within the `onSelect` method, the `buttonTextAfterSelection` method does not work and the selected value is reset to the initial value.

**Comment by AdelRedaa97** [comment]
A lot of changes were made in v4.0, take a look here
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
