### ISSUE TITLE
selectedRowStyle and selectedRowTextStyle properties are activated on the second selection

### ISSUE THREAD

**Issue by hasanhasanov** [AdelRedaa97/react-native-select-dropdown#161]
`type Model = { key: number; value: string; selected: boolean, }`

When I make a transaction using the model above, the following **features are activated on the second selection**.

`selectedRowStyle`
 `selectedRowTextStyle`

In the library example, these features work without any problems

**Comment by AdelRedaa97** [comment]
A lot of changes were made in v4.0, take a look here
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
