### ISSUE TITLE
autoscroll not working due to style array

### ISSUE THREAD

**Issue by Balaram-Singh** [AdelRedaa97/react-native-select-dropdown#162]
rowStyle={[styles.pickerRowStyle, {backgroundColor: themeConfigutation.getColor('#f4f3ef')}]}	
some thing like this breaks the height of row

**Comment by AdelRedaa97** [comment]
A lot of changes were made in v4.0, take a look here
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
