### ISSUE TITLE
Bottom border shown after last element

### ISSUE THREAD

**Issue by chrisfougner** [AdelRedaa97/react-native-select-dropdown#170]
I'd like to be able to show a divider only between items, not also at the end. I don't see an option to do this.

![image](https://github.com/AdelRedaa97/react-native-select-dropdown/assets/30043591/90ae9c5c-3a92-429f-b0ca-67a659f9e5c3)

**Comment by khiemk31** [comment]
same issues :(

**Comment by khiemk31** [comment]
hey bro i can fix that issues with :
  rowStyle={{
          borderBottomWidth: 0,
        }}

**Comment by chrisfougner** [comment]
Yeah that applies it to all rows, and removes the divider everywhere. I only want it removed from the very last row.

**Comment by AdelRedaa97** [comment]
Fixed in v4.0 take a look at the changes made in v4.0
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
