### ISSUE TITLE
Possible to Always open Dropdown to Appear Top of Screen?

### ISSUE THREAD

**Issue by sikandarchishty** [AdelRedaa97/react-native-select-dropdown#172]
hey, is there anyway to always open Dropdown with Search on Top of Screen. Also fixes the issue when keyboard is open.

I have a really large amount of data, would really love to have this.

![IMG_5755](https://github.com/AdelRedaa97/react-native-select-dropdown/assets/19312954/e6d501d5-a33b-4fd5-b880-e1409fe9cbad)

Thanks & keep up the good work.

**Comment by AdelRedaa97** [comment]
Currently, the dropdown appears only under the button you can update it and patch the file

find this file react-native-select-dropdown/src/hooks/useLayoutDropdown.js
after line 71 add your position, it should be at the end of the return {}
