### ISSUE TITLE
TypeError: iterator method is not callable

### ISSUE THREAD

**Issue by AliHassan5927** [AdelRedaa97/react-native-select-dropdown#177]
TypeError: The iterator method is not callable, I'm getting this error when setting search to false, when 'search' is true, it's working fine but on false, the app crashes. Also when setting search value to undefined instead of false, it works fine

**Comment by Josher29** [comment]
Same here! 
I had to set null as default instead false and it works

**Comment by AdelRedaa97** [comment]
Fixed in v4.0 take a look at the changes made in v4.0
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
