### ISSUE TITLE
Wrap text in a row

### ISSUE THREAD

**Issue by brokerdim** [AdelRedaa97/react-native-select-dropdown#178]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-select-dropdown@3.4.0` for the project I'm working on. I can't place long lines of text (for 2 lines, usually it is more than enough) in IOS into a single option row. Solutions written here don't help me (on iOS) https://github.com/AdelRedaa97/react-native-select-dropdown/issues/55

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-select-dropdown/src/SelectDropdown.js b/node_modules/react-native-select-dropdown/src/SelectDropdown.js
index 18f66b0..a744fd9 100644
--- a/node_modules/react-native-select-dropdown/src/SelectDropdown.js
+++ b/node_modules/react-native-select-dropdown/src/SelectDropdown.js
@@ -158,7 +158,7 @@ const SelectDropdown = (
             <View style={styles.dropdownCustomizedRowParent}>{renderCustomizedRowChild(item, index, isSelected)}</View>
           ) : (
             <Text
-              numberOfLines={1}
+              numberOfLines={2}
               allowFontScaling={false}
               style={mergeStyles(styles.dropdownRowText, rowTextStyle, isSelected && selectedRowTextStyle)}>
               {rowTextForSelection ? rowTextForSelection(item, index) : item.toString()}
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AdelRedaa97** [comment]
Fixed in v4.0 take a look at the changes made in v4.0
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes
