### ISSUE TITLE
Custom dropdown width (not the same as the button width)

### ISSUE THREAD

**Issue by P1rMD** [AdelRedaa97/react-native-select-dropdown#20]
Hi, is it possible to set a custom dropdown width (see attached screenshot)?
Tried to find it in docs or examples, but was unsuccessful.
It would be a great feature to have such an opportunity.
![scrn](https://user-images.githubusercontent.com/17233053/136508096-4446c037-1448-4736-8e53-1fa4de45e9c7.png)

**Comment by yoilerlp** [comment]
Same issue
