### ISSUE TITLE
No Typescript declaration files

### ISSUE THREAD

**Issue by Seanmclem** [AdelRedaa97/react-native-select-dropdown#3]
There are no typescript declarations for this library. It would be great if there were. I might add some myself and PR if it's not a priority, but in 2021, it really should be.

Thanks

**Comment by seaophiel** [comment]
it would be great

**Comment by AdelRedaa97** [comment]
i've added declaration file check this out => https://github.com/AdelRedaa97/react-native-select-dropdown/blob/master/index.d.ts

**Comment by seaophiel** [comment]
Many thanks!
