### ISSUE TITLE
Remove bottom border on dropdownStyle

### ISSUE THREAD

**Issue by unit-002** [AdelRedaa97/react-native-select-dropdown#30]
![image](https://user-images.githubusercontent.com/79749223/141648506-5725922a-85c2-4921-8a63-32c187a18e4c.png)

is there a way to remove the white line or that bottom border in between option as shown on image?

it has no effect changing the border color on dropdownStyle.

**Comment by uriFrischman** [comment]
I found that setting the following on `rowStyle` removes the bottom line:

`rowStyle: {
         ....
        borderBottomColor:  null,
        borderBottomWidth: null
    }`
