### ISSUE TITLE
Detect when picker is open or closed

### ISSUE THREAD

**Issue by ClaudioCampuzano** [AdelRedaa97/react-native-select-dropdown#31]
Is there a way to access these states through e.g. focus and blur methods?

Very good complement, thank you very much

**Comment by AdelRedaa97** [comment]
if you mean to change dropdown icon there is a parameter in renderDropdownIcon is added to detect if it's opened look code example below

`
renderDropdownIcon={(isOpened) => {
  return (
    <FontAwesome
      name={isOpened ? "chevron-up" : "chevron-down"}
      color={"#FFF"}
      size={18}
    />
  );
}}
`
