### ISSUE TITLE
It works normally when you click it, but next is abnormal. (ios)

### ISSUE THREAD

**Issue by jhui134** [AdelRedaa97/react-native-select-dropdown#35]
- platform : iOS
- react-native-select-dropdown version : 1.4.0

1. SelectDropdown button click
2. Click anything.
3. SelectDropdown button click retry is fail

testcode
`<View style={{ flex: 1, backgroundColor: '#000' }}>
      <Text>TestScreen</Text>
      <View style={{ flex: 1, width }}>
        <ScrollView
          showsVerticalScrollIndicator={false}
          alwaysBounceVertical={false}
          contentContainerStyle={{
            flexGrow: 1,
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingVertical: '10%',
          }}
        >
          <SelectDropdown
            data={countries}
            defaultValueByIndex={1} // use default value by index or default value
            defaultValue={'Canada'} // use default value by index or default value
            onSelect={(selectedItem, index) => {
              console.log(selectedItem, index);
            }}
            buttonTextAfterSelection={(selectedItem, index) => {
              return selectedItem;
            }}
            rowTextForSelection={(item, index) => {
              return item;
            }}
          />
        </ScrollView>
      </View>
    </View>`

**Comment by AdelRedaa97** [comment]
I have tried this code and it worked fine
