### ISSUE TITLE
If a value is already selected and then i open the dropdown, it gets autoscrolled to this preselected value.

### ISSUE THREAD

**Issue by PrakashGiri21** [AdelRedaa97/react-native-select-dropdown#37]
1.Selected a value and clicked out
2.Opened the dropdown again
3.It gets autoscrolled to this previous selected value

It makes sense for large list, but not with 12-15 items.Please provide an option to turn this autoscroll off.
Thanks and Regards.

**Comment by AdelRedaa97** [comment]
disableAutoScroll prop added to disable auto scrolling in v1.6
