### ISSUE TITLE
Cannot have a list with less, or more than 3 options

### ISSUE THREAD

**Issue by Seanmclem** [AdelRedaa97/react-native-select-dropdown#4]
If the dropdown only has 2 options, an empty 3rd option is always shown. If the dropdown has 4 or more options, it still only shows 3. Exactly 3 is the only thing you get apparently

**Comment by AdelRedaa97** [comment]
thats because the dropdown default height is 150 and each option inside dropdown has default height 50 so when there is only 2 options it appears that there is an empty 3rd option ,,, you can custom dropdown height by using dropdownStyle prop and you can change each option height too by using rowStyle prop

**Comment by Seanmclem** [comment]
> thats because the dropdown default height is 150 and each option inside dropdown has default height 50 so when there is only 2 options it appears that there is an empty 3rd option ,,, you can custom dropdown height by using dropdownStyle prop and you can change each option height too by using rowStyle prop 

OK, that is a work-around. Is that really the desired behavior? Seems like the height should automatically be based on the number of options.  I suppose I could do it manually, but I've already completely rewritten my select-list code to accommodate a different component.

Unless you're going to fix them, I still might make a PR or 2 to address some concerns of mine. If you're open to them

**Comment by AdelRedaa97** [comment]
Okay, i know its not the best solution ,, I will make the height of dropdown based on no of options and there will be a maximum height for the dropdown.

**Comment by AdelRedaa97** [comment]
Hello Sean, height automatically set based on the number of options in v 1.0.7
