### ISSUE TITLE
Use with react-native-web

### ISSUE THREAD

**Issue by dsound-zz** [AdelRedaa97/react-native-select-dropdown#45]
We are using react-native-web which keeps web and native in one code base using a shared folder. All code is native first.

Can this library be used for web as well?

**Comment by Balaram-Singh** [comment]
I am getting

ERROR in ./node_modules/react-native-select-dropdown/src/SelectDropdown.js 138:6
Module parse failed: Unexpected token (138:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const renderFlatlistItem = ({item, index}) => {
|     return (
>       <TouchableOpacity style={{...styles.dropdownRow, ...rowStyle}} onPress={() => onSelectItem(item, index)}>
|         {renderCustomizedRowChild ? (
|           <View style={styles.dropdownCustomizedRowParent}>{renderCustomizedRowChild(item, index)}</View>
 @ ./node_modules/react-native-select-dropdown/index.js 1:0-50 3:15-29
