### ISSUE TITLE
How to display dropdown full width and height

### ISSUE THREAD

**Issue by hypesol** [AdelRedaa97/react-native-select-dropdown#47]
Hi
I want to show dropdown in full width and height. How can i do this?

Thanks

**Comment by MathieuRA** [comment]
To follow up. I have the same problem

**Comment by AdelRedaa97** [comment]
Do you want the dropdown to take screen's full height and width? I don't think the dropdown will  look good

**Comment by Taofiqq** [comment]
@AdelRedaa97 Is there no customizable styling on the select component?

**Comment by AdelRedaa97** [comment]
> @AdelRedaa97 Is there no customizable styling on the select component?

use ```selectedRowStyle``` and ```selectedRowTextStyle``` for styling the selected component they are added in v2.0.0
