### ISSUE TITLE
Android Select Dropdown

### ISSUE THREAD

**Issue by Taofiqq** [AdelRedaa97/react-native-select-dropdown#49]
Hi @AdelRedaa97, Why is the dropdown not displaying well on androind?

<img width="293" alt="image" src="https://user-images.githubusercontent.com/61933245/162609657-3b3c6436-2f9f-4b6d-a7f0-71e6f0f73a9b.png">

**Comment by AdelRedaa97** [comment]
It's not about android, it's about the height between the dropdown button and the end of the screen, if there is enough height between the dropdown button and the end of the screen the dropdown will be displayed under the button, if not it will be displayed above the button.
