### ISSUE TITLE
Select dropdown item take too munch time?

### ISSUE THREAD

**Issue by zeeshan-shabbir** [AdelRedaa97/react-native-select-dropdown#50]
I am using  "react-native-select-dropdown": "^1.11.0", when i clicked on drop down item it freeze/hang for some time then select item . i am attaching gif of behavior
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/80969033/162897786-afb3aeed-b80b-428d-8772-93fe636c94cc.gif)

**Comment by AdelRedaa97** [comment]
I have made some changes, Could you try v"1.12.0" and tell me you still facing the same issue

**Comment by zeeshan-shabbir** [comment]
I tried to find the issue  ,I found dropdown delay only when i am changing state only.
delaying the app ,
 `   <SelectDropdown
                    data={Items}
                    onSelect={(selectedItem, index) => {
                        if(onvalueChange=='null')return null
                        onvalueChange(selectedItem)
                    }}
/>
`
run smoothly 
 `   <SelectDropdown
                    data={Items}
                    onSelect={(selectedItem, index) => {
                  //do nothing run fine.
                    }}
/>
`

**Comment by zeeshan-shabbir** [comment]
> I have made some changes, Could you try v"1.13.0" and tell me you still facing the same issue

ok I will upgrade version and inform you.
