### ISSUE TITLE
Change Touchable Opacity . 

### ISSUE THREAD

**Issue by zeeshan-shabbir** [AdelRedaa97/react-native-select-dropdown#51]
I want to change Touchable opacity when selected items. i can not figure out  how to do this

**Comment by amalte** [comment]
+1

**Comment by AdelRedaa97** [comment]
use ```selectedRowStyle``` and ```selectedRowTextStyle``` for styling the selected component they are added in v2.0.0

**Comment by valn1** [comment]
Sorry, but this does not fix the issue as the opacity is set here int he lib:
`<TouchableOpacity
          disabled={disabledIndexs?.includes(index)}
          activeOpacity={0.8}
          style={mergeStyles(styles.dropdownRow, rowStyle, isSelected && selectedRowStyle)}
          onPress={() => onSelectItem(item, index)}>
          {renderCustomizedRowChild ? (
            <View style={styles.dropdownCustomizedRowParent}>{renderCustomizedRowChild(item, index, isSelected)}</View>
          ) : (
            <Text
              numberOfLines={1}
              allowFontScaling={false}
              style={mergeStyles(styles.dropdownRowText, rowTextStyle, isSelected && selectedRowTextStyle)}>
              {rowTextForSelection ? rowTextForSelection(item, index) : item.toString()}
            </Text>
          )}
        </TouchableOpacity>`
        
        for someone to change the active opacity, they would need to actively edit the lib using a patch to change the value directly
