### ISSUE TITLE
Android Dropdown gap

### ISSUE THREAD

**Issue by jorge-o-murillo** [AdelRedaa97/react-native-select-dropdown#52]
Hi @AdelRedaa97, thanks for this great repo.

I have an issue on Android where the Dropdown displays a gap between the button and the dropdown items. I copy/pasted the exact code provided in the `demo1.js` file on a reproducible snack: [link](https://snack.expo.dev/@jorgeomurillo/sandbox-react-native)
<img width="312" alt="Screen Shot 2022-04-12 at 1 01 00 PM" src="https://user-images.githubusercontent.com/75639668/163043978-7fa1ca3c-bbe3-4082-bae0-9d5f726c6e4b.png">

iOS does not have this issue. Any help on this? Thanks.

**Comment by AdelRedaa97** [comment]
The problem is android's StatusBar try to use this prop in Dropdown ```statusBarTranslucent={true}```
https://github.com/AdelRedaa97/react-native-select-dropdown#statusBarTranslucent

Please tell me if this issue still exist.

**Comment by jorge-o-murillo** [comment]
Thanks, adding `<StatusBar translucent={false} />` worked.

**Comment by AdelRedaa97** [comment]
You can add this prop ```statusBarTranslucent={true}``` in <DropDown /> will work too if you want to make android's StatusBar translucent is true

**Comment by jorge-o-murillo** [comment]
Hi there @AdelRedaa97, unfortunately on Android devices with a top notch thje `statusBarTranslucent={true}` doesn't work properly. For example, if you try running this same code on a Samsung S10 ([link](https://snack.expo.dev/@jorgeomurillo/sandbox-react-native)), it will turn out like this:
<img width="400" alt="Screen Shot 2022-04-26 at 6 05 07 PM" src="https://user-images.githubusercontent.com/75639668/165417807-048c9c51-57ca-4ff0-bfa8-50ffff19f06b.png">

Any Android device with a top notch has this issue (Pixel 4A, Samsung S10, etc.). May be related to previous RN bugs: [link](https://github.com/facebook/react-native/issues/23693)

**Comment by LuizHGodoy** [comment]
already try use SafeAreaView? works fine for me here with statusBarTranslucent={true} inside the SafeAreaView
