### ISSUE TITLE
Unable to set default value as first value of array in data props

### ISSUE THREAD

**Issue by bingchuan93** [AdelRedaa97/react-native-select-dropdown#54]
Hihi! Im unable to set the first value in the array in data props if the first value is 0.

Eg. [0, 5, 10], i cant set defaultValue={0} nor defaultValueByIndex={0} to let default value be the value '0'
Doing this will revert the box value to the placeholder instead of '0'

tia

**Comment by AdelRedaa97** [comment]
Which version do you use?

**Comment by bingchuan93** [comment]
I'm using 1.11.0. @AdelRedaa97

**Comment by AdelRedaa97** [comment]
I have made some changes, Could you try v"1.12.0" and tell me if it still not working

**Comment by bingchuan93** [comment]
Hi @AdelRedaa97 !

Its still not working. I'm guessing its because `selectedItem` is 0 and reverts to the falsey part of the ternary operator when rendering.
<img width="880" alt="image" src="https://user-images.githubusercontent.com/15227023/163762859-ab879a5f-3488-4d07-b110-1f8940254e52.png">

**Comment by AdelRedaa97** [comment]
Thanks for reporting ❤️ it's fixed now in v"1.13.0" let me know if it still not working

**Comment by bingchuan93** [comment]
Yes it works now! thanks much!
