### ISSUE TITLE
The `disabled` property does not actually disable the button

### ISSUE THREAD

**Issue by Pkcarreno** [AdelRedaa97/react-native-select-dropdown#57]
Adding the `disabled` property does not have any impact on the button, it continues to work normally, I force pass true and false values and in both cases it does nothing

In addition to this, it would also be useful to be able to define styles for the button and text when it's disabled, something like:
`disabledButtonStyle` and `disabledButtonTextStyle`, to match the rest of the property names used in the component

or just a parameter to add a color and opacity value when disabled

Thank you very much for this component.

Note: I only tested on android

**Comment by sami3898** [comment]
Hey, @Pkcarreno have achieved this functionality for disabling style?

**Comment by Pkcarreno** [comment]
Hey @sami3898, I created an internal implementation that uses `react-native-select-dropdown` and what I did was to manipulate the styles manually with inline styles according to the `disabled` value that I passed to my component.
