### ISSUE TITLE
How can I set a value externally in the Select Dropdown?

### ISSUE THREAD

**Issue by 360macky** [AdelRedaa97/react-native-select-dropdown#71]
## Case
I have a select list of items `A`, `B` and `C`. And through a button I want the selected item to be item `C`.

**How can I change the value selected outside the SelectDropdown element?**

Thanks in advance!

**Comment by AdelRedaa97** [comment]
if you are asking to set a default value you can use ```defaultValue```, If you are asking for a method that you can call it by using the ref, It's not implemented yet I think it's an important feature to be added I'll work on it.

**Comment by 360macky** [comment]
> if you are asking to set a default value you can use `defaultValue`, If you are asking for a method that you can call it by using the ref, It's not implemented yet I think it's an important feature to be added I'll work on it.

Hi Adel! Yes, I'm asking for a method that I can call it using a ref. Not the `defaultValue`.
I achieved that feature with #72.

**Comment by AdelRedaa97** [comment]
```selectIndex(index)``` this function is added in v3.0.0 to select an option from outside the component using a ```ref```

**Comment by 360macky** [comment]
Great! Thanks @AdelRedaa97 🎉
