### ISSUE TITLE
Not selecting on first click.

### ISSUE THREAD

**Issue by kali-musquare** [AdelRedaa97/react-native-select-dropdown#73]
i'm using this component inside  ScrollView(in parent component)->Array.Map->Child Component(react-native-select-dropdown);

**Comment by AdelRedaa97** [comment]
If the button is inside a scrollview or flatlist you have to add ```keyboardShouldPersistTaps="always"``` prop in the parent scrollview or flatlist

**Comment by kali-musquare** [comment]
already used keyboardShouldPersistTaps="always" but no use.

closed ticket.

**Comment by AdelRedaa97** [comment]
Which

**Comment by waymond91** [comment]
I am also having this problem on Android. Items on the drop down have to be selected twice.

**Comment by AdelRedaa97** [comment]
Which version do you use?
