### ISSUE TITLE
Need placeholder text when passing empty data

### ISSUE THREAD

**Issue by MahiBuger** [AdelRedaa97/react-native-select-dropdown#74]
When we passing empty data loader is showing inside dropdown like below,
<img width="311" alt="Screenshot 2022-06-22 at 3 17 04 PM" src="https://user-images.githubusercontent.com/51189214/174999094-207e89c6-bf6f-42aa-8d29-b4672edb9ade.png">

Instead loader can we have customizable place holder text

**Comment by paridha16** [comment]
same issue

**Comment by AdelRedaa97** [comment]
The loader is removed in v3.0.0
