### ISSUE TITLE
Search can't find data when the list of data is too long.

### ISSUE THREAD

**Issue by rahmanda-wa** [AdelRedaa97/react-native-select-dropdown#79]
And it behave differently across different android device, on some device it able to find the data, but on other device the search only work for a certain length of data list. For instance if i have a list of 150 customer, the search can only find the first 100 customer in the list. Thank you in advance for the help, sorry for my bad english.

**Comment by AdelRedaa97** [comment]
What is the length of the list?

**Comment by AdelRedaa97** [comment]
I think it's the same issue here https://github.com/AdelRedaa97/react-native-select-dropdown/issues/69

**Comment by rahmanda-wa** [comment]
it can show all the data in the dropdown with no problem, it just wouldn't show the search result if the data list is too long

**Comment by kkkasio** [comment]
I think I have the same problem, I have a long list of Az.
If you look up the value directly from a word at the end of the list, no filtering result is generated.

I also think it could be something related to the size of the list.

**Comment by rahmanda-wa** [comment]
not really, i'm just stuck with it for now

**Comment by sbozzella** [comment]
Hi, i am facing now the same behaviour: i have a long list of data and the search function doesn't find last elements of the list. 

How can i resolve it?

**Comment by nikhil3010** [comment]
@kkkasio @sbozzella @AdelRedaa97 @rahmanda-wa  i solve this issue by removing a code from  react-native-select-dropdown/src/helpers/deepSearchInArr.js  at. line number 34 i remove else part  here i attach a screen shot of it
![Screenshot 2022-09-09 at 6 04 00 PM](https://user-images.githubusercontent.com/19788892/189350878-f59fae88-fca2-4b51-b002-83d0d8c9a7a0.png)

**Comment by AdelRedaa97** [comment]
```onScrollEndReached``` prop is added for pagination in v3.0.0 and also ```onChangeSearchInputText``` to make your custom search function outside the component

**Comment by fede4954** [comment]
@AdelRedaa97 this doesn't fix the issue out of the box, I'm on 3.0.0 and search on my app's dropdowns is still broken where the list of data is too long (breaks where I have over 150 items for example)

I modified the file as @nikhil3010 said and that fixed it
