### ISSUE TITLE
if index > 3

### ISSUE THREAD

**Issue by ataideworkspace** [AdelRedaa97/react-native-select-dropdown#8]
First of all congratulations for the excellent work. When I put more than 3 items, the following error occurs. Thanks for listening
<img width="304" alt="Screenshot 2021-07-15 at 14 18 36" src="https://user-images.githubusercontent.com/63284120/125787043-aebb7978-6841-4936-950c-df12c5ab1ab3.png">

**Comment by AdelRedaa97** [comment]
thanks for your interest this issue is now fixed in v1.0.9
