### ISSUE TITLE
Bottom navigation bar changes to white color, on `onSelect` event

### ISSUE THREAD

**Issue by nandor23** [AdelRedaa97/react-native-select-dropdown#90]
When onSelect event is triggered the navigation bar changes its color. I tried to change even the the navbar color, when the Dropdown is focused, but it instantly switches back to white color....

**Comment by ferretwithaberet** [comment]
I also ran into this issue. Did you find any fixes?

**Comment by AdelRedaa97** [comment]
Big changes have been made in v4.0 take a look here
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists
