### ISSUE TITLE
Search functionality not showing

### ISSUE THREAD

**Issue by sbozzella** [AdelRedaa97/react-native-select-dropdown#91]
Hi, i want to use dropdown menù with search functionality but it doesn't work. I mean i have enabled correctly "search" but nothing happen.
This is a part of the code:
```
let city = ['Rome', 'New York', 'Ottawa', 'Venice', 'Paris'];
<SelectDropdown
                data = {city}
                onSelect={(selectedItem, index) => {
                  this.setState({ operatorSelected: selectedItem })
                }}
                buttonTextAfterSelection={(selectedItem, index) => {
                  return selectedItem
                }}
                rowTextForSelection={(item, index) => {
                  return item
                }}
                renderDropdownIcon={isOpened => {
                  return <FontAwesome name={isOpened ? 'chevron-up' : 'chevron-down'} color={'#004975'} size={18} />;
                }}
                search
                dropdownIconPosition={'right'}
                defaultButtonText={'Lista degli operatori'}
                buttonStyle={styles.dropdownBtnStyle}
                buttonTextStyle={styles.dropdownBtnTxtStyle}
              />
```
And this is the version:
`    "react-native-select-dropdown": "^2.0.1",`

This is a screen of my application:
![IMG_20220906_161414__01](https://user-images.githubusercontent.com/73956205/188668981-6dbe7677-e175-4913-83b3-afe991790f47.png)

I tried also implementing Demo 3 but also doesn't appear:
![IMG_20220906_170322__01](https://user-images.githubusercontent.com/73956205/188670514-eed24908-bb5a-49fc-ae0a-39709ace5582.jpg)

Thank you.

**Comment by AdelRedaa97** [comment]
You have to add ```search``` inside component

**Comment by sbozzella** [comment]
Yes of course i have added search inside component but doesn't work.

`let city = ['Rome', 'New York', 'Ottawa', 'Venice', 'Paris'];
<SelectDropdown
                data = {city}
                onSelect={(selectedItem, index) => {
                  this.setState({ operatorSelected: selectedItem })
                }}
                buttonTextAfterSelection={(selectedItem, index) => {
                  return selectedItem
                }}
                rowTextForSelection={(item, index) => {
                  return item
                }}
                renderDropdownIcon={isOpened => {
                  return <FontAwesome name={isOpened ? 'chevron-up' : 'chevron-down'} color={'#004975'} size={18} />;
                }}
                **search** // here
                dropdownIconPosition={'right'}
                defaultButtonText={'Lista degli operatori'}
                buttonStyle={styles.dropdownBtnStyle}
                buttonTextStyle={styles.dropdownBtnTxtStyle}
              />`

**Comment by AdelRedaa97** [comment]
could you try the latest version ```2.0.4``` and please inform me if it's still not working

**Comment by sbozzella** [comment]
I have installed the latest version:

![package-json](https://user-images.githubusercontent.com/73956205/188907034-c492268e-9163-4772-92be-00c92464720c.png)

but it's still not working:

![Screenshot_20220907-163810_CPR_Macchine_App_Mobile](https://user-images.githubusercontent.com/73956205/188907146-5021dd2d-4b65-41d3-be55-25b1da9dc38c.jpg)

I am developing on a physical device with Android 12.

Do you have any suggestion?

Thank you.

**Comment by sbozzella** [comment]
i don't know how but now search function appear and works but seems that it isn't able to find data in a long list :\

**Comment by AdelRedaa97** [comment]
```onScrollEndReached``` prop is added for pagination in v3.0.0 and also ```onChangeSearchInputText``` to make your custom search function outside the component
