### ISSUE TITLE
Required select dropdown field

### ISSUE THREAD

**Issue by sbozzella** [AdelRedaa97/react-native-select-dropdown#96]
Is possibile to make select dropdown value required? Could be added to a form in a class component?

I have different select dorpdown in the same screen and i want that user has to select each one before an event (click of button). 

Thank you.

**Comment by AdelRedaa97** [comment]
Save the returned value from the select dropdown in your component state and make the initial value to be null and in your validator function check if the state has a value or still null "user didn't choose an option"
