### ISSUE TITLE
Row child with a JSX element

### ISSUE THREAD

**Issue by sbozzella** [AdelRedaa97/react-native-select-dropdown#97]
Hi, 
i want to show in row child a list of item and just one button as first (or last) element of the list to give the possibility to the user to perform an event (in my case to navigate to another screen).

I tried with renderCustomizedRowChild but it add the button to all rows. I need just one button.

Thank you :)

**Comment by AdelRedaa97** [comment]
Can you clarify more or add a photo of what you want to achieve?
