### ISSUE TITLE
Dropdown Style will not work with dynamic values.

### ISSUE THREAD

**Issue by jlm0** [AdelRedaa97/react-native-select-dropdown#99]
The dropdown style doesn't work with dynamic styles. For example, if the dropdown receives a dynamic `backgroundColor` style from the parent components state (or global state) it will not adjust its stylings. The `buttonStyle `will adjust to the same dynamic variable but the dropdown won't. For example expo snack where the onSelect changes a state color value. It appropriately changes the background of the button but not the dropdowns: 
https://snack.expo.dev/x5K3sXCw0

**Comment by AdelRedaa97** [comment]
fixed in version "3.0.3" try it in your example and tell me if it still not working

**Comment by jlm0** [comment]
Test it out on the snack example. Works great. Thanks! Will try it out in my project.
